project:
  type: website
  output-dir: C:\Users\zyt2023.stu\OneDrive - UBC\Attachments\Canada_life\UBC\MGEM\github\E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

